./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat.sh -b s3://euliaa-l2/TESTS/Kuehlungsborn/L2A/ -o s3://euliaa-daily/Kuehlungsborn/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Kuehlungsborn
./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat.sh -b s3://euliaa-l2/TESTS/Kuehlungsborn/L2A/ -o s3://euliaa-daily/Kuehlungsborn/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Kuehlungsborn
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Andoya/L2A/ -o s3://euliaa-daily/Andoya/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Andoya
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Andoya/L2A/ -o s3://euliaa-daily/Andoya/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Andoya
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/OHP/L2A/ -o s3://euliaa-daily/OHP/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign OHP
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/OHP/L2A/ -o s3://euliaa-daily/OHP/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign OHP
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Jungfraujoch/L2A/ -o s3://euliaa-daily/Jungfraujoch/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Jungfraujoch
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Jungfraujoch/L2A/ -o s3://euliaa-daily/Jungfraujoch/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Jungfraujoch
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Payerne/L2A/ -o s3://euliaa-daily/Payerne/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Payerne
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Payerne/L2A/ -o s3://euliaa-daily/Payerne/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Payerne
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Maido/L2A/ -o s3://euliaa-daily/Maido/ -t 20MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Maido
# ./home/oper/euliaa_proc/euliaa_proc/scripts/daily_concat_runner.sh -b s3://euliaa-l2/Maido/L2A/ -o s3://euliaa-daily/Maido/ -t 60MIN -c /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml --campaign Maido