campaign_name: Andoya
hdf5_file:
config: /home/oper/euliaa_proc/euliaa_proc/config/config_nc/config_nc_Andoya.yaml
config_eprofile_wind: /home/oper/euliaa_proc/euliaa_proc/config/config_eprofile_wind.yaml
# config_eprofile_bsc:  /home/oper/euliaa_proc/euliaa_proc/config/config_eprofile_bsc.yaml
config_qc: /home/oper/euliaa_proc/euliaa_proc/config/config_qc_w_correction.yaml # if needed, create a new qc config file specific for campaign
output_nc_dir: s3://euliaa-l2/Andoya/ # for L2A and L2B products

# E-Profile DWL configuration
output_nc_eprofile_wind_dir: s3://euliaa-eprofile/EProfile_DWL/Andoya/ # for E-Profile DWL products, stored on our own internal s3 bucket
eprofile_wind_prefix: 'L1_EU1WL_' # should be L1_EU1WL_ or L1_EU2WL_ depending on the instrument
s3cfg_eprofile_path: /home/oper/.s3cfg_eprofile # comment this line to stop uploading on E-Profile DWL s3 bucket
output_nc_eprofile_wind_dir_DL: s3://eprofile-dl-l1/ # comment this line to stop uploading on E-Profile DWL s3 bucket

output_bufr_dir: s3://euliaa-l2/BUFR/Andoya/ # if MCH transfer of temperature, may need to adapt in a similar way as for E-Profile buckets
bufr_types:
  #- wind
  - temperature

# OLD
# fig_dir: s3://euliaa-quicklooks/Andoya/
# fig_prefix: euliaa_quicklook_
