hdf5_file:
config: /home/acbr/euliaa_postproc/configs/config_nc.yaml
config_qc: /home/acbr/euliaa_postproc/configs/config_qc1.yaml
output_nc_dir: /data/euliaa-l2/TESTS/
output_bufr_dir: /data/euliaa-l2/TESTS_BUFR/