
attributes:
  Conventions: CF-1.8
  campaign_name: EULIAA-JFJ
  license:
  version: 1.0
  references:
  wigos_station_id: 0-20000-0-06730
  wmo_id: 
  instrument_type: 'high_spectral_resolution_lidar'
  instrument_id: EULIAA_2
  instrument_serial_number: 
  instrument_wavelength: 386 # wavelength of the laser in nm
  instrument_model: EULIAA
  instrument_manufacturer:
  site_location: Jungfraujoch Research Facility (Sphinx Observatory), Switzerland
  station_altitude: 3562.
  station_latitude: 46.54
  station_longitude: 7.98
  history:
  institution: Leibniz Institute for Atmospheric Physics, Kuehlungsborn
  comment:
  principal_investigator:
  conventions:
  operation_mode: 'campaign'
    # original_hdf5:
    #   hdf5_group: glo
    #   hdf5_var_name: Mode
  retrieval_code_version: '0'
    # original_hdf5:
    #   hdf5_group: glo
    #   hdf5_var_name: Version
  retrieval_code: # Algorithm should include description of both measurement method, retrieval and correction / postproc (or split into several fields)
  retrieval_reference:
  calibration_status:
  calibration_time:
  height_above_ground:
  date_of_installation:
  maintenance: #preventive and corrective maintenance (recommended and scheduled maintenance and calibration procedures, including frequency, and a description of procedures)
  comparison_to_reference: #results of comparison with travelling standards
