MAX_ALTITUDE: 60000.
SNR_THRES:
  w_mie: 5 # -
  u_mie: 0 # -
  v_mie: 0 # -
  temperature_int: 0 # -
  backscatter_coef: 5 # -
ERR_THRES:
  w_mie: 1 # m/s
  u_mie: 1 # m/s
  v_mie: 1 # m/s
  temperature_int: 5 # K
  backscatter_coef: .inf
THRES_MIN:
  w_mie: -40.96
  u_mie: -409.6
  v_mie: -409.6
  temperature_int: 0
  backscatter_coef: 0 # m-1 sr-1
THRES_MAX:
  w_mie: 40.96
  u_mie: 409.6
  v_mie: 409.6
  temperature_int: 409.5
  backscatter_coef: .inf

CORRECTION: 28.8461 # temporary correction to do remove when fixed by IAP
VARS_TO_KEEP:
- altitude
- temperature
- w
- v
- u
- temperature_flag
- w_flag
- v_flag
- u_flag
- station_latitude
- station_longitude
- station_altitude
- range_integration
- time_integration
