# config file for setting logs destination and level #
#####################################################

logger_name: 'euliaa_proc_runner'


# configure logging to console (stdout). Logging to stdout is enabled in any case
# -------------------------------------------------------------------------------
loglevel_stdout: INFO  # level specification acceptable for logging module (DEBUG, INFO, WARNING, ERROR, CRITICAL)

# configure logging to file (only takes effect if write_logfile is set True)
# CARE: Each run generates a new file. Consider while specifying timestamp_format to avoid overwriting
# ----------------------------------------------------------------------------------------------------
write_logfile: True
logfile_path: euliaa_proc/logs/  # absolute or relative to project dir
logfile_basename: euliaa_proc  # full filename will be logfile_basename + timestamp + logfile_ext
logfile_ext: .log  # file extension for logs files
logfile_timestamp_format: '%Y%m%d%H%M%S'  # valid format for datetime's strftime()
loglevel_file: INFO  # level specification acceptable for logging module
