hdf5_file:
config: /home/oper/euliaa_proc/euliaa_proc/config/config_nc_20250820.yaml
config_eprofile: /home/oper/euliaa_proc/euliaa_proc/config/config_eprofile_wind.yaml
config_qc: /home/oper/euliaa_proc/euliaa_proc/config/config_qc2.yaml
output_nc_dir: s3://euliaa-l2/TESTS_KBORN/
output_bufr_dir: s3://euliaa-l2/TESTS_KBORN_BUFR/
bufr_types:
  #- wind
  - temperature
fig_dir: s3://euliaa-quicklooks/TESTS_KBORN/
fig_prefix: euliaa_quicklook_