hdf5_file:
config: /home/oper/euliaa_proc/euliaa_proc/config/config_nc_Maido.yaml
config_eprofile_wind: /home/oper/euliaa_proc/euliaa_proc/config/config_eprofile_wind.yaml
config_eprofile_bsc:  /home/oper/euliaa_proc/euliaa_proc/config/config_eprofile_bsc.yaml
config_qc: /home/oper/euliaa_proc/euliaa_proc/config/config_qc.yaml
output_nc_dir: s3://euliaa-l2/TESTS/Maido/
output_nc_eprofile_wind_dir: s3://euliaa-l2/EProfile_DWL/Maido/
# s3cfg_eprofile_path: /home/oper/.s3cfg_eprofile
# output_nc_eprofile_wind_dir_DL: s3://eprofile-dl-l1/
eprofile_wind_prefix: 'L1_EU2WL_'
chm_template_file: '/home/oper/euliaa_proc/data/20251001_pay_CHM200110_0920_000.nc'
output_nc_eprofile_bsc_dir: s3://euliaa-l2/EProfile_ALC/Maido/
# upload_to_UKMO_FTP: 1
eprofile_bsc_prefix: '99901_B'
eprofile_bsc_suffix: '_CHM15k'
output_bufr_dir: s3://euliaa-l2/TESTS_BUFR/Maido/
bufr_types:
  #- wind
  - temperature
fig_dir: s3://euliaa-quicklooks/TESTS/Maido/
fig_prefix: euliaa_quicklook_