hdf5_file:
config: /home/acbr/euliaa_proc/euliaa_proc/config/config_nc.yaml
config_qc: /home/acbr/euliaa_proc/euliaa_proc/config/config_qc1.yaml
output_nc_dir: /data/euliaa-l2/TESTS/
output_bufr_dir: /data/euliaa-l2/TESTS_BUFR/
bufr_types:
  - wind
  - temperature
fig_dir: /data/euliaa-quicklooks/TESTS/
fig_prefix: euliaa_